apiVersion: v1
kind: Pod
metadata:
  name: model-indexer
  namespace: crater-workspace
spec:
  restartPolicy: Never
  containers:
  - name: indexer
    image: ubuntu:22.04
    command: ["/bin/bash", "-lc", "sleep infinity"]
    volumeMounts:
    - name: crater-rox-storage
      mountPath: /mnt/crater-rox-storage
      readOnly: true
    - name: crater-storage
      mountPath: /mnt/crater-storage
      readOnly: true
    - name: lucid-pvc
      mountPath: /mnt/lucid-pvc
      readOnly: true
  volumes:
  - name: crater-rox-storage
    persistentVolumeClaim:
      claimName: crater-rox-storage
      readOnly: true
  - name: crater-storage
    persistentVolumeClaim:
      claimName: crater-storage
      readOnly: true
  - name: lucid-pvc
    persistentVolumeClaim:
      claimName: lucid-pvc
      readOnly: true
